from src.year2025.day07 import parse, part1, part2

example_input = """.......S.......
.......|.......
.......^.......
......|^|......
......|.|......
.....|^|^|.....
.....|.|.|.....
....|^|^|^|....
....|.|.|.|....
...|^|^|||^|...
...|.|.|||.|...
..|^|^|||^|^|..
..|.|.|||.|.|..
.|^|||^||.||^|.
.|.|||.||.||.|.
|^|^|^|^|^|||^|
|.|.||.|.|||.|."""

# NOTE: The example input in description contains '|' which represents BEAMS, not the manifold map itself.
# The map itself should only contain 'S', '.', and '^'.
# "You quickly locate a diagram of the tachyon manifold (your puzzle input)."
# The example input block in Part 1 description shows two blocks:
# One with just S, ., ^.
# One with beams | overlaid.
# I should use the one WITHOUT beams for testing logic, but the visual one helps to verify.
# The Example Input text block:
# ```
# .......S.......
# ...............
# .......^.......
# ...............
# ......^.^......
# ...............
# .....^.^.^.....
# ...............
# ....^.^...^....
# ...............
# ...^.^...^.^...
# ...............
# ..^...^.....^..
# ...............
# .^.^.^.^.^...^.
# ...............
# ```
# Wait, this specific block (first large block in description) seems to be the input.
# Let's use that.

clean_example_input = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

def test_part1():
    parsed = parse(clean_example_input)
    result = part1(parsed)
    print(f"Part 1 Example Result: {result}")
    assert result == 21, f"Expected 21, got {result}"

def test_part2():
    parsed = parse(clean_example_input)
    result = part2(parsed)
    print(f"Part 2 Example Result: {result}")
    assert result == 40, f"Expected 40, got {result}"

if __name__ == "__main__":
    test_part1()
    test_part2()
    print("Test Passed!")

